import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  sidebardatagrid: [
    'welcome',
    'sample-applications',
    {
      type: 'category',
      label: 'Migrating from Prev versions',
      link: {
        type: 'generated-index',
        description: 'In this section you will find information on how to migrate from previous versions of Xceed DataGrid for WPF as well as information on how to migrate to Xceed DataGrid for WPF from Xceed Grid for .NET.',            
      },
      items: ['migrating-from-prev/01','migrating-from-prev/02','migrating-from-prev/03','migrating-from-prev/04','migrating-from-prev/05','migrating-from-prev/06','migrating-from-prev/07'],
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        description: 'In this topic you will find the necessary information to get you started using Xceed DataGrid for WPF.',            
      },
      items: ['getting-started/creating-first','getting-started/licensing','getting-started/desing-time-support','getting-started/expression-blend','getting-started/deploying','getting-started/07','getting-started/08'],
    },
    {
      type: 'category',
      label: 'Object Model Overview',
      link: {
        type: 'doc',
        id: 'datagrid/object-model-view/overview',
      },
      items: [
        {
          type: 'category',
          label: 'DataGridControl Class',
          link: {
            type: 'doc',
            id: 'datagrid/object-model-view/datagrid-control-class/datagrid-control-class',
          },
          items: ['datagrid/object-model-view/datagrid-control-class/datagrid-context-class'],
        },
        'datagrid/object-model-view/cell-class',
        {
          type: 'category',
          label: 'Column Class',
          link: {
            type: 'doc',
            id: 'datagrid/object-model-view/column-class/column-class',
          },
          items: ['datagrid/object-model-view/column-class/position-width'],
        },
        'datagrid/object-model-view/row-class',
        {
          type: 'category',
          label: 'DataGridCollectionView Class',
          link: {
            type: 'doc',
            id: 'datagrid/object-model-view/datagrid-collectionview-class/datagrid-collectionview-class',
          },
          items: ['datagrid/object-model-view/datagrid-collectionview-class/datagrid-detaildescription'],
        },
        'datagrid/object-model-view/other-class',        
      ],
    },
    {
      type: 'category',
      label: 'DataGrid Fundamentals',
      link: {
        type: 'generated-index',
        description: 'In this section, you will find a variety of information and examples that explain and demonstrate the fundamentals of Xceed DataGrid for WPF.',
      },
      items: [
        {
          type: 'category',
          label: 'Providing Data',
          link: {
            type: 'doc',
            id: 'datagrid/fundamentals/providing-inserting-remove/overview',
          },
          items: [
            'datagrid/fundamentals/providing-inserting-remove/data-virtualization',
            'datagrid/fundamentals/providing-inserting-remove/inserting-data',
            'datagrid/fundamentals/providing-inserting-remove/removing-data',
            'datagrid/fundamentals/providing-inserting-remove/unbound-data',
            {
              type: 'category',
              label: 'Master/Detail',
              link: {
                type: 'doc',
                id: 'datagrid/fundamentals/providing-inserting-remove/master-detail/overview',
              },
              items: [
                'datagrid/fundamentals/providing-inserting-remove/master-detail/datagrid-contexts',
                'datagrid/fundamentals/providing-inserting-remove/master-detail/detail-configuration',
                'datagrid/fundamentals/providing-inserting-remove/master-detail/view-properties',
                'datagrid/fundamentals/providing-inserting-remove/master-detail/detail-description',
                'datagrid/fundamentals/providing-inserting-remove/master-detail/custom-detail-description',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Editing and Validating Data Overview',
          link: {
            type: 'doc',
            id: 'datagrid/fundamentals/editing-validating/overview',
          },
          items: [
            'datagrid/fundamentals/editing-validating/datagridcollection-edit-event',
            'datagrid/fundamentals/editing-validating/routed-edit-event',
            'datagrid/fundamentals/editing-validating/cell-editors',
            'datagrid/fundamentals/editing-validating/date-time-editor',
            'datagrid/fundamentals/editing-validating/masked-editor',
            'datagrid/fundamentals/editing-validating/numeric-editors',
            'datagrid/fundamentals/editing-validating/text-value-editors',
            'datagrid/fundamentals/editing-validating/validation',
            'datagrid/fundamentals/editing-validating/cell-error-styles',
          ],
        },  
        {
          type: 'category',
          label: 'Filtering Data',
          link: {
            type: 'doc',
            id: 'datagrid/fundamentals/filtering/overview',
          },
          items: [
            'datagrid/fundamentals/filtering/filter-row',
            'datagrid/fundamentals/filtering/custom-autofiltering-control',
            'datagrid/fundamentals/filtering/advanced-filtering',
          ],
        },  
        {
          type: 'category',
          label: 'Grouping Data',
          link: {
            type: 'doc',
            id: 'datagrid/fundamentals/grouping/overview',
          },
          items: [
            'datagrid/fundamentals/grouping/grouping-configuration',
            'datagrid/fundamentals/grouping/custom-group-config-selector',
          ],
        },
        'datagrid/fundamentals/sorting',  
        'datagrid/fundamentals/searching',
        {
          type: 'category',
          label: 'Statistical Functions',
          link: {
            type: 'doc',
            id: 'datagrid/fundamentals/statical-functions/overview',
          },
          items: [
            'datagrid/fundamentals/statical-functions/creating-statistical-functions',
          ],
        },
        {
          type: 'category',
          label: 'Views and Themes',
          link: {
            type: 'doc',
            id: 'datagrid/fundamentals/views-themes/overview',
          },
          items: [
            {
              type: 'category',
              label: 'Views',
              link: {
                type: 'generated-index',
                description: 'In this section of the documenation, you will find information and examples about the various views provided by Xceed DataGrid for WPF.',
              },
              items: [
                'datagrid/fundamentals/views-themes/views/card-views',
                {
                  type: 'category',
                  label: 'Cardflow 3D View',
                  link: {
                    type: 'doc',
                    id: 'datagrid/fundamentals/views-themes/views/cardflow-3d-view/cardflow-3d-view',
                  },
                  items: [
                    'datagrid/fundamentals/views-themes/views/cardflow-3d-view/multisurface-view-overview',
                    'datagrid/fundamentals/views-themes/views/cardflow-3d-view/camera-setting',
                    'datagrid/fundamentals/views-themes/views/cardflow-3d-view/tips-for-improving-3d-performance',
                  ],
                },
                {
                  type: 'category',
                  label: 'Table, Tableflow and TreeGridFlow Views',
                  link: {
                    type: 'doc',
                    id: 'datagrid/fundamentals/views-themes/views/table-tableflow-treegrid-view/overview',
                  },
                  items: [
                    'datagrid/fundamentals/views-themes/views/table-tableflow-treegrid-view/column-position-width',
                    'datagrid/fundamentals/views-themes/views/table-tableflow-treegrid-view/merged-column-header',
                    'datagrid/fundamentals/views-themes/views/table-tableflow-treegrid-view/spanned-cell',
                    'datagrid/fundamentals/views-themes/views/table-tableflow-treegrid-view/view-properties',
                    'datagrid/fundamentals/views-themes/views/table-tableflow-treegrid-view/tableview-smooth-scrolling-and-other',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Themes',
              link: {
                type: 'doc',
                id: 'datagrid/fundamentals/views-themes/themes/overview',
              },
              items: [
                'datagrid/fundamentals/views-themes/themes/system-themes',
                'datagrid/fundamentals/views-themes/themes/office-2007-themes',
                'datagrid/fundamentals/views-themes/themes/other-themes',
                {
                  type: 'category',
                  label: 'Multi-surface Themes',
                  link: {
                    type: 'doc',
                    id: 'datagrid/fundamentals/views-themes/themes/multisurface-themes/overview',
                  },
                  items: [
                    'datagrid/fundamentals/views-themes/themes/multisurface-themes/surface-configuration',
                    'datagrid/fundamentals/views-themes/themes/multisurface-themes/elemental-themes',
                    'datagrid/fundamentals/views-themes/themes/multisurface-themes/chamaleon-theme',
                  ],
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Styles',
          link: {
            type: 'doc',
            id: 'datagrid/fundamentals/styles/styles',
          },
          items: [
            'datagrid/fundamentals/styles/cell-error-styles',
          ],
        },
        {
          type: 'category',
          label: 'Templates',
          link: {
            type: 'doc',
            id: 'datagrid/fundamentals/templates/templates',
          },
          items: [
            'datagrid/fundamentals/templates/datagridpagecontrol-template',
          ],
        },
        'datagrid/fundamentals/clipboard-support',
        'datagrid/fundamentals/commands',
        'datagrid/fundamentals/exporting',
        'datagrid/fundamentals/foreign-key-detection',
        'datagrid/fundamentals/items-containers',
        'datagrid/fundamentals/mvvm-support',
        'datagrid/fundamentals/printing-exporting-to-xps',
        'datagrid/fundamentals/automation-testing',
        'datagrid/fundamentals/ui-virtualization',
        'datagrid/fundamentals/unbound-columns',
      ],
    },
    {
      type: 'category',
      label: 'Code Snippets',
      link: {
        type: 'doc',
        id: 'datagrid/code-snippets/overview',            
      },
      items: [
        'datagrid/code-snippets/01',
        'datagrid/code-snippets/02',
        'datagrid/code-snippets/03',
        'datagrid/code-snippets/04',
        'datagrid/code-snippets/05',
        'datagrid/code-snippets/06',
        'datagrid/code-snippets/07',
        'datagrid/code-snippets/08',
        'datagrid/code-snippets/09',
        'datagrid/code-snippets/10',
        'datagrid/code-snippets/11',
        'datagrid/code-snippets/12',
        'datagrid/code-snippets/13',
        'datagrid/code-snippets/14',
        'datagrid/code-snippets/15',
        'datagrid/code-snippets/16',
        'datagrid/code-snippets/17',
        'datagrid/code-snippets/18',
        'datagrid/code-snippets/19',
        'datagrid/code-snippets/20',
        'datagrid/code-snippets/21',
        'datagrid/code-snippets/22',
        'datagrid/code-snippets/23',
        'datagrid/code-snippets/24',
        'datagrid/code-snippets/25',
        'datagrid/code-snippets/26',
        'datagrid/code-snippets/27',
        'datagrid/code-snippets/28',
        'datagrid/code-snippets/29',
        'datagrid/code-snippets/30',
        'datagrid/code-snippets/31',
        'datagrid/code-snippets/32',
        'datagrid/code-snippets/33',
        'datagrid/code-snippets/34',
        'datagrid/code-snippets/35',
        'datagrid/code-snippets/36',
        'datagrid/code-snippets/37',
      ],
    },
    {
      type: 'category',
      label: 'Creating a Custom Theme',
      link: {
        type: 'doc',
        id: 'datagrid/creating-custom-theme/overview',            
      },
      items: [
        'datagrid/creating-custom-theme/01', 
        'datagrid/creating-custom-theme/02', 
        'datagrid/creating-custom-theme/03', 
        'datagrid/creating-custom-theme/04', 
        'datagrid/creating-custom-theme/05', 
      ],
    },
    'source-code-info',
    'contact-info',
    
  ],
};

export default sidebars;
