import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'welcome',
    'themes-usage-instructions',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/01',
      },
      items: ['getting-started/02','getting-started/03','getting-started/04','getting-started/05','getting-started/06','getting-started/07','getting-started/08'],
    },
    'chart',
    {
      type: 'category',
      label: 'Datagrid control',
      link: {
        type: 'doc',
        id: 'datagrid/intro',
      },
      items: [
        'datagrid/object-model-overview',
        'datagrid/datagrid-control-class',
        'datagrid/datagridcontext-class',
        'datagrid/cell-class',
        {
          type: 'category',
          label: 'Column control',
          link: {
            type: 'doc',
            id: 'datagrid/column/intro',
          },
          items: [
            'datagrid/column/position-width',],
        },
        'datagrid/row-class',
        'datagrid/datagridcollectionview-class',
        'datagrid/other-classes',
        {
          type: 'category',
          label: 'Manipulating data',
          link: {
            type: 'generated-index',
            description: 'In this section, you will find a variety of information and examples that explain and demonstrate how to manipulate data using Xceed DataGrid for WPF.',            
          },
          items: 
          [
            {
              type: 'category',
              label: 'Providing, Inserting and Removing Data',
              link: {
                type: 'doc',
                id: 'datagrid/manipulating-data/providing-inserting-removing/01',
              },
              items: [
                 'datagrid/manipulating-data/providing-inserting-removing/02'
                ,'datagrid/manipulating-data/providing-inserting-removing/03'
                ,'datagrid/manipulating-data/providing-inserting-removing/04'],
            },
            {
              type: 'category',
              label: 'Editing and Validating Data',
              link: {
                type: 'doc',
                id: 'datagrid/manipulating-data/editing-validating-data/01',
              },
              items: [
                 ,'datagrid/manipulating-data/editing-validating-data/02'
                 ,'datagrid/manipulating-data/editing-validating-data/03'
                 ,'datagrid/manipulating-data/editing-validating-data/04'
                 ,'datagrid/manipulating-data/editing-validating-data/05'
                 ,'datagrid/manipulating-data/editing-validating-data/06'
                 ,'datagrid/manipulating-data/editing-validating-data/07'
                 ,'datagrid/manipulating-data/editing-validating-data/08'
                 ,'datagrid/manipulating-data/editing-validating-data/09'
                 ,'datagrid/manipulating-data/editing-validating-data/10'
                 ,'datagrid/manipulating-data/editing-validating-data/11'
                ],
            },
            {
              type: 'category',
              label: 'Grouping Data',
              link: {
                type: 'doc',
                id: 'datagrid/manipulating-data/grouping-data/01',
              },
              items: [
                 ,'datagrid/manipulating-data/grouping-data/02'
                 ,'datagrid/manipulating-data/grouping-data/03'
                ],
            },
            'datagrid/manipulating-data/sorting',
            'datagrid/manipulating-data/filtering',            
          ],
        },
        {
          type: 'category',
          label: 'Views and themes',
          link: {
            type: 'doc',
            id: 'datagrid/views-themes/intro',
          },
          items: [
            {
              type: 'category',
              label: 'Views',
              link: {
                type: 'doc',
                id: 'datagrid/views-themes/views/01',
              },
              items: 
              [
                'datagrid/views-themes/views/02',
                'datagrid/views-themes/views/03',
                'datagrid/views-themes/views/04',
              ],
            },
            {
              type: 'category',
              label: 'Themes',
              link: {
                type: 'doc',
                id: 'datagrid/views-themes/themes/01',
              },
              items: 
              [
                'datagrid/views-themes/themes/02',
                'datagrid/views-themes/themes/03',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Styles',
          link: {
            type: 'doc',
            id: 'datagrid/styles/intro',
          },
          items: 
          [
            'datagrid/styles/01',
          ],
        },
        'datagrid/templates',
        'datagrid/commands',
        'datagrid/foreign-key-detection',
        'datagrid/items-containers',
        'datagrid/ui-automation-testing',
        'datagrid/unbound-columns',
        'datagrid/comparing-datagrids',
      ],
    },
    {
      type: 'category',
      label: 'Listbox control',
      link: {
        type: 'doc',
        id: 'listbox/01',
      },
      items: 
      [
        'listbox/02',
        'listbox/03',
        'listbox/04',
        'listbox/05',
        'listbox/06',
        'listbox/07',
        'listbox/08',
        'listbox/09',
        {
          type: 'category',
          label: 'Panels & Views',
          link: {
            type: 'generated-index',
            description: 'Xceed\'s WPF listbox provides panels that can be used directly via the the listbox\'s ItemsPanel property and views that can be used in the specialized MultiViewPanel.',
          },
          items: 
          [
            'listbox/panel-view/01',
            'listbox/panel-view/02',
            'listbox/panel-view/03',
          ],
        },
      ],
    },
    'docking-window-control',
    'material-controls',
    'property-grid',
    /*{
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },*/
  ],
};

export default sidebars;
