import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  sidebardatagrid: [
    'welcome',
    'sample-applications',
    {
      type: 'category',
      label: 'Migrating from Prev versions',
      link: {
        type: 'generated-index',
        description: 'In this section you will find information on how to migrate from previous versions of Xceed DataGrid for WPF as well as information on how to migrate to Xceed DataGrid for WPF from Xceed Grid for .NET.',            
      },
      items: ['migrating-from-prev/01','migrating-from-prev/02','migrating-from-prev/03','migrating-from-prev/04','migrating-from-prev/05','migrating-from-prev/06','migrating-from-prev/07'],
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        description: 'In this topic you will find the necessary information to get you started using Xceed DataGrid for WPF.',            
      },
      items: ['getting-started/creating-first','getting-started/licensing','getting-started/desing-time-support','getting-started/expression-blend','getting-started/deploying'],
    },
    {
      type: 'category',
      label: 'Object Model Overview',
      link: {
        type: 'doc',
        id: 'object-model-view/overview',
      },
      items: [
        {
          type: 'category',
          label: 'DataGridControl Class',
          link: {
            type: 'doc',
            id: 'object-model-view/datagrid-control-class/datagrid-control-class',
          },
          items: ['object-model-view/datagrid-control-class/datagrid-context-class'],
        },
        'object-model-view/cell-class',
        {
          type: 'category',
          label: 'Column Class',
          link: {
            type: 'doc',
            id: 'object-model-view/column-class/column-class',
          },
          items: ['object-model-view/column-class/position-width'],
        },
        'object-model-view/row-class',
        {
          type: 'category',
          label: 'DataGridCollectionView Class',
          link: {
            type: 'doc',
            id: 'object-model-view/datagrid-collectionview-class/datagrid-collectionview-class',
          },
          items: ['object-model-view/datagrid-collectionview-class/datagrid-detaildescription'],
        },
        'object-model-view/other-class',        
      ],
    },
    {
      type: 'category',
      label: 'DataGrid Fundamentals',
      link: {
        type: 'generated-index',
        description: 'In this section, you will find a variety of information and examples that explain and demonstrate the fundamentals of Xceed DataGrid for WPF.',
      },
      items: [
        {
          type: 'category',
          label: 'Providing Data',
          link: {
            type: 'doc',
            id: 'fundamentals/providing-inserting-remove/overview',
          },
          items: [
            'fundamentals/providing-inserting-remove/data-virtualization',
            'fundamentals/providing-inserting-remove/inserting-data',
            'fundamentals/providing-inserting-remove/removing-data',
            'fundamentals/providing-inserting-remove/unbound-data',
            {
              type: 'category',
              label: 'Master/Detail',
              link: {
                type: 'doc',
                id: 'fundamentals/providing-inserting-remove/master-detail/overview',
              },
              items: [
                'fundamentals/providing-inserting-remove/master-detail/datagrid-contexts',
                'fundamentals/providing-inserting-remove/master-detail/detail-configuration',
                'fundamentals/providing-inserting-remove/master-detail/view-properties',
                'fundamentals/providing-inserting-remove/master-detail/detail-description',
                'fundamentals/providing-inserting-remove/master-detail/custom-detail-description',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Editing and Validating Data Overview',
          link: {
            type: 'doc',
            id: 'fundamentals/editing-validating/overview',
          },
          items: [
            'fundamentals/editing-validating/datagridcollection-edit-event',
            'fundamentals/editing-validating/routed-edit-event',
            'fundamentals/editing-validating/cell-editors',
            'fundamentals/editing-validating/date-time-editor',
            'fundamentals/editing-validating/masked-editor',
            'fundamentals/editing-validating/numeric-editors',
            'fundamentals/editing-validating/text-value-editors',
            'fundamentals/editing-validating/validation',
            'fundamentals/editing-validating/cell-error-styles',
            'fundamentals/editing-validating/foreign-key-detection'
          ],
        },  
        {
          type: 'category',
          label: 'Filtering Data',
          link: {
            type: 'doc',
            id: 'fundamentals/filtering/overview',
          },
          items: [
            'fundamentals/filtering/filter-row',
            'fundamentals/filtering/custom-autofiltering-control',
            'fundamentals/filtering/advanced-filtering',
          ],
        },  
        {
          type: 'category',
          label: 'Grouping Data',
          link: {
            type: 'doc',
            id: 'fundamentals/grouping/overview',
          },
          items: [
            'fundamentals/grouping/grouping-configuration',
            'fundamentals/grouping/custom-group-config-selector',
          ],
        },
        'fundamentals/sorting',  
        'fundamentals/searching',
        {
          type: 'category',
          label: 'Statistical Functions',
          link: {
            type: 'doc',
            id: 'fundamentals/statical-functions/overview',
          },
          items: [
            'fundamentals/statical-functions/creating-statistical-functions',
          ],
        },
        {
          type: 'category',
          label: 'Views and Themes',
          link: {
            type: 'doc',
            id: 'fundamentals/views-themes/overview',
          },
          items: [
            {
              type: 'category',
              label: 'Views',
              link: {
                type: 'generated-index',
                description: 'In this section of the documenation, you will find information and examples about the various views provided by Xceed DataGrid for WPF.',
              },
              items: [
                'fundamentals/views-themes/views/card-views',
                {
                  type: 'category',
                  label: 'Cardflow 3D View',
                  link: {
                    type: 'doc',
                    id: 'fundamentals/views-themes/views/cardflow-3d-view/cardflow-3d-view',
                  },
                  items: [
                    'fundamentals/views-themes/views/cardflow-3d-view/multisurface-view-overview',
                    'fundamentals/views-themes/views/cardflow-3d-view/camera-setting',
                    'fundamentals/views-themes/views/cardflow-3d-view/tips-for-improving-3d-performance',
                  ],
                },
                {
                  type: 'category',
                  label: 'Table, Tableflow and TreeGridFlow Views',
                  link: {
                    type: 'doc',
                    id: 'fundamentals/views-themes/views/table-tableflow-treegrid-view/overview',
                  },
                  items: [
                    'fundamentals/views-themes/views/table-tableflow-treegrid-view/column-position-width',
                    'fundamentals/views-themes/views/table-tableflow-treegrid-view/merged-column-header',
                    'fundamentals/views-themes/views/table-tableflow-treegrid-view/spanned-cell',
                    'fundamentals/views-themes/views/table-tableflow-treegrid-view/view-properties',
                    'fundamentals/views-themes/views/table-tableflow-treegrid-view/tableview-smooth-scrolling-and-other',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Themes',
              link: {
                type: 'doc',
                id: 'fundamentals/views-themes/themes/overview',
              },
              items: [
                'fundamentals/views-themes/themes/system-themes',
                'fundamentals/views-themes/themes/office-2007-themes',
                'fundamentals/views-themes/themes/other-themes',
                {
                  type: 'category',
                  label: 'Multi-surface Themes',
                  link: {
                    type: 'doc',
                    id: 'fundamentals/views-themes/themes/multisurface-themes/overview',
                  },
                  items: [
                    'fundamentals/views-themes/themes/multisurface-themes/surface-configuration',
                    'fundamentals/views-themes/themes/multisurface-themes/elemental-themes',
                    'fundamentals/views-themes/themes/multisurface-themes/chamaleon-theme',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Background brushes',
              link: {
                type: 'doc',
                id: 'fundamentals/views-themes/background-brushes/overview',
              },
              items: [
                'fundamentals/views-themes/background-brushes/datagrid-brushes',
                'fundamentals/views-themes/background-brushes/card-brushes',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Styles',
          link: {
            type: 'doc',
            id: 'fundamentals/styles/styles',
          },
          items: [
            'fundamentals/styles/cell-error-styles',
          ],
        },
        {
          type: 'category',
          label: 'Templates',
          link: {
            type: 'doc',
            id: 'fundamentals/templates/templates',
          },
          items: [
            'fundamentals/templates/datagridpagecontrol-template',
          ],
        },
        'fundamentals/clipboard-support',
        'fundamentals/commands',
        'fundamentals/exporting',
        'fundamentals/foreign-key-detection',
        'fundamentals/items-containers',
        'fundamentals/mvvm-support',
        'fundamentals/persist-settings',
        'fundamentals/printing-exporting-to-xps',
        'fundamentals/automation-testing',
        'fundamentals/ui-virtualization',
        'fundamentals/unbound-columns',
      ],
    },
    {
      type: 'category',
      label: 'Code Snippets',
      link: {
        type: 'doc',
        id: 'code-snippets/overview',            
      },
      items: [
        'code-snippets/01',
        'code-snippets/02',
        'code-snippets/03',
        'code-snippets/04',
        'code-snippets/05',
        'code-snippets/06',
        'code-snippets/07',
        'code-snippets/08',
        'code-snippets/09',
        'code-snippets/10',
        'code-snippets/11',
        'code-snippets/12',
        'code-snippets/13',
        'code-snippets/14',
        'code-snippets/15',
        'code-snippets/16',
        'code-snippets/17',
        'code-snippets/18',
        'code-snippets/19',
        'code-snippets/20',
        'code-snippets/21',
        'code-snippets/22',
        'code-snippets/23',
        'code-snippets/24',
        'code-snippets/25',
        'code-snippets/26',
        'code-snippets/27',
        'code-snippets/28',
        'code-snippets/29',
        'code-snippets/30',
        'code-snippets/31',
        'code-snippets/32',
        'code-snippets/33',
        'code-snippets/34',
        'code-snippets/35',
        'code-snippets/36',
        'code-snippets/37',
      ],
    },
    {
      type: 'category',
      label: 'Creating a Custom Theme',
      link: {
        type: 'doc',
        id: 'creating-custom-theme/overview',            
      },
      items: [
        'creating-custom-theme/01', 
        'creating-custom-theme/02', 
        'creating-custom-theme/03', 
        'creating-custom-theme/04', 
        'creating-custom-theme/05', 
      ],
    },
    'source-code-info',
    'contact-info',    
  ],
};

export default sidebars;
